#!/usr/bin/env bash

set -e

TARGET="fluid"
BUILD_TYPE="Debug"
ARGS=(
    '--p-type=DOUBLE'
    '--v-type=FLOAT'
    '--v-flow-type=FIXED(32, 16)'
    'input.dat'
)
TYPES='DOUBLE,FLOAT,FIXED(32, 16)'

# Build
ROOT_DIR="$(realpath "$(dirname -- "$0")")"
BUILD_DIR="$ROOT_DIR/build"

mkdir -p "$BUILD_DIR"

cmake \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=true \
    -DCMAKE_BUILD_TYPE="$BUILD_TYPE" \
    -DTYPES="$TYPES" \
    -B "$BUILD_DIR" \
    -S "$ROOT_DIR"

# Link compile_commands.json
ln -sf "$BUILD_DIR/compile_commands.json" "$ROOT_DIR"

# Run
cmake --build "$BUILD_DIR" --target "$TARGET" -- -j4
"$BUILD_DIR/fluid" "${ARGS[@]}"
