#!/usr/bin/env bash

set -e

TARGET="fluid"
BUILD_TYPE="Debug"

# # More types, slow compilation:
# ARGS=(
#     '--p-type=DOUBLE'
#     '--v-type=FLOAT'
#     '--v-flow-type=FIXED(32, 16)'
#     'data.in'
# )
# TYPES='DOUBLE,FLOAT,FIXED(32, 16)'
# SIZES='S(14, 5),S(10, 10)'

# # Less types, faster compilation:
# ARGS=(
#     '--p-type=FIXED(32, 16)'
#     '--v-type=FIXED(32, 16)'
#     '--v-flow-type=FIXED(32, 16)'
#     'data.in'
# )
# TYPES='FIXED(32, 16)'
# SIZES='S(14, 5)'

# For benchmarking
BUILD_TYPE="Release"
ARGS=(
    '--p-type=FIXED(32, 16)'
    '--v-type=FIXED(32, 16)'
    '--v-flow-type=FIXED(32, 16)'
    '--ticks=400'
    '--quiet=true'
    'data_heavy.in'
)
TYPES='FIXED(32, 16)'
SIZES='S(36, 84),S(36, 85)'

# Build
ROOT_DIR="$(realpath "$(dirname -- "$0")")"
BUILD_DIR="$ROOT_DIR/build"

mkdir -p "$BUILD_DIR"

cmake \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=true \
    -DCMAKE_BUILD_TYPE="$BUILD_TYPE" \
    -DTYPES="$TYPES" \
    -DSIZES="$SIZES" \
    -B "$BUILD_DIR" \
    -S "$ROOT_DIR"

# Link compile_commands.json
ln -sf "$BUILD_DIR/compile_commands.json" "$ROOT_DIR"

# Run
cmake --build "$BUILD_DIR" --target "$TARGET" -- -j4
"$BUILD_DIR/fluid" "${ARGS[@]}"
